"""add notes api and linked to todos api

Revision ID: 9891d28693f3
Revises: 3b93f40290df
Create Date: 2026-03-25 08:31:49.769640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9891d28693f3'
down_revision: Union[str, Sequence[str], None] = '3b93f40290df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_todos_note_id_notes'), 'notes', ['note_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_todos_note_id_notes'), type_='foreignkey')

    # ### end Alembic commands ###
